### ISSUE TITLE
Has Ford had problems crossing nodes (machines)?

### ISSUE THREAD

**Issue by sunce4t** [minghust/ford#2]
Hello, I'm using the rlib library in ford for cross-node experiments, but after the qp connection, the RDMA read always gives an error:
**[qp_impl.hpp:140] poll till completion error: 12 transport retry counter exceeded**
So, has Ford encountered the problems? And if so, hope to know how to solve it. Thanks!

**Comment by minghust** [comment]
Thanks for reaching out!
We haven't encountered this problem. The error code (12) in RDMA programming doc (https://docs.nvidia.com/networking/display/rdmaawareprogrammingv17/events#src-34256581_Events-IBV_WC_RETRY_EXC_ERR) shows that this is because a sender is unable to receive feedback from the receiver. I suggest to double check the network connnection status and machine configurations.
